config/routes.rb
Rails.application.routes.draw do
  
  get 'toppages/index'
  root to: 'toppages#index'
  
  get 'questions/index'
  resources :inquiries, only: [:new, :create]
  get 'introductions/index'
  get 'jobs/index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get :search, on: :collection
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  
  resources :words, only:[:show, :create, :edit, :update, :destroy] do
    collection do
      get :eiken
      get :toeic
      get :confirmation
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :favorites, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :words, dependent: :destroy
  # フォロー機能
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow, dependent: :destroy
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverses_of_relationship, source: :user, dependent: :destroy
  # お気に入り機能
  has_many :favorites, dependent: :destroy
  has_many :favorite_words, through: :favorites, source: :word, dependent: :destroy
  # 画像アップロードの処理
  mount_uploader :image, ImageUploader
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def favorite(other_word)
      self.favorites.find_or_create_by(word_id: other_word.id)
  end
  
  def unfavorite(other_word)
    favorite = self.favorites.find_by(word_id: other_word.id)
    favorite.destroy if favorite
  end
  
  def favorite?(other_word)
    self.favorite_words.include?(other_word)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only:[:index, :show, :edit, :destroy, :followings, :followers]
  before_action :correct_user_word, only:[:show]
  before_action :correct_user, only:[:edit]
  before_action :correct_user_destroy, only:[:destroy]
  
  
  def index
    @users = User.where(teacher: false).order(id: :desc).page(params[:page]).per(30)
  end

  def show
    @word = Word.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(edit_params)
      flash[:success] = "プロフィールを更新しました。"
      redirect_to likes_user_path(@user)
    else
      flash.now[:danger] = "プロフィールを更新できませんでした。"
      render :edit
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to root_url
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page]).per(30)
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page]).per(30)
    counts(@user)
  end
  
  def likes
    @user = User.find(params[:id])
    @favorites = @user.favorite_words.page(params[:page]).per(30)
    counts(@user)
    
  end
  
  def search
    if params[:name].present?
      @users = User.where(teacher: false).where('name LIKE ?', "%#{params[:name]}%")
    else
      @users = User.none
    end
    @users = @users.page(params[:page]).per(30)
  end
  
  private
  
  def correct_user
    @user = User.find_by(id: params[:id])
    unless @user == current_user
      redirect_to root_url
    end
  end
  
  def correct_user_destroy
    @user = User.find_by(id: params[:id])
    unless @user == current_user
      flash[:danger] = "自分の詳細ページで退会してください。"
      redirect_to likes_user_path(current_user)
    end
  end
  
  def correct_user_word
    @user = User.where(teacher: true)
    unless @user == current_user
      flash[:danger] = "このページへはアクセスできません"
      redirect_to likes_user_path(current_user)
    end
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def edit_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :eikenlevel, :toeiclevel, :goal, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_users.html.erb
<% if users.any? %>
  <div class="row">
    <% users.each do |user| %>
      <div class="col-12 col-sm-6 col-md-4 mb-2">
        <div class="card text-center pt-3 pb-3 shadow" style="padding: 25px;">
          <% if user.image? %>
            <%= image_tag user.image.thumb.url, :size => '30x30', class: "user-image mx-auto d-block" %>
          <% else %>
            <%= image_tag "default.jpg", :size => '30x30', class: "mx-auto d-block" %>
          <% end %>
          <div><%= user.name %></div>
          <p><%= link_to 'View profile', likes_user_path(user) %></p>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="container mx-auto" style="width: 80vw">
  <h1><%= @user.name %> のプロフィール編集ページ</h1>
  
  
  <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    
    <div class="form-group">
      <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
    </div>
    
    <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :email, "Email" %>
        <%= f.email_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :password, "Password" %>
        <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="form-group d-inline-flex">
      <div>
        <%= f.label :eikenlevel, "英語の試験" %><br>
        <%= f.select :eikenlevel, [["1級", "英語の試験 1級"], ["準1級", "英語の試験 準1級"], ["2級", "英語の試験 2級"], ["準2級", "英語の試験 準2級"], ["3級", "英語の試験 3級"], ["4級", "英語の試験 4級"], ["5級", "英語の試験 5級"], ["未取得", ""]], include_blank: "選択して下さい" %>
      </div>
      <div class="ml-2">
        <%= f.label :toeiclevel, "TIOEC" %><br>
        <%= f.select :toeiclevel, [["900~990", "TIOEC 900~990"], ["800~895", "TIOEC 800~895"], ["700~795", "TIOEC 700~795"], ["600~695", "TIOEC 600~695"], ["500~595", "TIOEC 500~595"], ["~495", "TIOEC ~495"], ["未取得", ""]], include_blank: "選択して下さい", class: "ml-2" %>
      </div>
    </div>
    
    
    <div class="form-group">
        <%= f.label :goal, "Goal" %>
        <%= f.text_area :goal, class: "form-control" %>
    </div>
    
    <%= f.submit "プロフィールを変更", class: "btn btn-primary btn-block mb-4" %>
              
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="container mx-auto" style="width: 80vw">
    <div class="row">
      <div class="col-12 col-sm-6 text-center">
        <% if @user.image? %>
          <%= image_tag @user.image.thumb.url, class: "user-image" %>
        <% else %>
          <%= image_tag "default.jpg", :size => '150x150', class: "mx-auto d-block" %>
        <% end %>
        <div>
          <h3 class="text-center mt-2"><%= @user.name %></h3>
        </div>
        <%= render "relationships/follow_button", user: @user %>
      </div>
      <div class="col-12 col-sm-6 p-0">
        <div class="d-inline-flex">
          <p>レベル：</p>
          <div class="mb-3">
            <p><%= @user.eikenlevel %></p>
            <p><%= @user.toeiclevel %></p>
          </div>
        </div>
        <p class="mb-3" style="word-wrap: break-word;">目標：<%= @user.goal %></p>
        <% if @user == current_user %>
          <div class="border-bottom"><%= link_to "プロフィールを編集", edit_user_path(@user), class: "btn btn-info mb-3" %></div>
        <% end %>
        <p class="mt-3">試験：
          <%= link_to "英語の試験", eiken_words_path, class: "btn btn-success ml-2" %>
          <%= link_to "TIOEC", toeic_words_path, class: "btn btn-warning ml-2" %>
        </p>
      </div>
      <div class="col-12 mt-4">
        <ul class="nav nav-tabs nav-justified mb-3">
          <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Vocabulary  <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
          <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
          <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
        </ul>
        <%= render 'users', users: @followers %>
      </div>
    </div>
  </div>

app/views/users/followings.html.erb
<div class="container mx-auto" style="width: 80vw">
    <div class="row">
      <div class="col-12 col-sm-6 text-center">
        <% if @user.image? %>
          <%= image_tag @user.image.thumb.url, class: "user-image" %>
        <% else %>
          <%= image_tag "default.jpg", :size => '150x150', class: "mx-auto d-block" %>
        <% end %>
        <div>
          <h3 class="text-center mt-2"><%= @user.name %></h3>
        </div>
        <%= render "relationships/follow_button", user: @user %>
      </div>
      <div class="col-12 col-sm-6 p-0">
        <div class="d-inline-flex">
          <p>レベル：</p>
          <div class="mb-3">
            <p><%= @user.eikenlevel %></p>
            <p><%= @user.toeiclevel %></p>
          </div>
        </div>
        <p class="mb-3" style="word-wrap: break-word;">目標：<%= @user.goal %></p>
        <% if @user == current_user %>
          <div class="border-bottom"><%= link_to "プロフィールを編集", edit_user_path(@user), class: "btn btn-info mb-3" %></div>
        <% end %>
        <p class="mt-3">試験：
          <%= link_to "英語の試験", eiken_words_path, class: "btn btn-success ml-2" %>
          <%= link_to "TIOEC", toeic_words_path, class: "btn btn-warning ml-2" %>
        </p>
      </div>
      <div class="col-12 mt-4">
        <ul class="nav nav-tabs nav-justified mb-3">
          <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Vocabulary  <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
          <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
          <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
        </ul>
        <%= render 'users', users: @followings %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<div class="container mx-auto" style="width: 80vw">
    <h3>ユーザー一覧</h3>
    <p class="d-flex justify-content-end mb-3"><%= link_to "ユーザー検索ページへ", search_users_path %></p>
    <% if @users.any? %>
        <div class="row">
            <% @users.each do |user| %>
                <div class="col-12 col-sm-6 col-md-4 mb-2">
                    <div class="card text-center pt-3 pb-3 shadow" style="padding: 25px;">
                        <% if user.image? %>
                            <%= image_tag user.image.url, :size => '30x30', class: "user-image mx-auto d-block" %>
                        <% else %>
                            <%= image_tag "/assets/default.jpg", :size => '30x30', class: "mx-auto d-block" %>
                        <% end %>
                        <div><%= user.name%></div>
                        <p><%= link_to 'View profile', likes_user_path(user) %></p>
                    </div>
                </div>
            <% end%>
        </div>
        <%= paginate @users %>
    <% end %>
</div>

app/views/users/likes.html.erb
<div class="container mx-auto" style="width: 80vw">
    <div class="row">
      <div class="col-12 col-sm-6 text-center">
        <% if @user.image? %>
          <%= image_tag @user.image.thumb.url, class: "user-image" %>
        <% else %>
          <%= image_tag "default.jpg", :size => '150x150', class: "mx-auto d-block" %>
        <% end %>
        <div>
          <h3 class="text-center mt-2"><%= @user.name %></h3>
        </div>
        <%= render "relationships/follow_button", user: @user %>
      </div>
      <div class="col-12 col-sm-6 p-0">
        <div class="d-inline-flex">
          <p>レベル：</p>
          <div class="mb-3">
            <p><%= @user.eikenlevel %></p>
            <p><%= @user.toeiclevel %></p>
          </div>
        </div>
        <p class="mb-3" style="word-wrap: break-word;">目標：<%= @user.goal %></p>
        <% if @user == current_user %>
          <div><%= link_to "プロフィールを編集", edit_user_path(@user), class: "btn btn-info mb-3" %></div>
        <% end %>
        <p class="border-top pt-3 m-0">試験：
          <%= link_to "英語の試験", eiken_words_path, class: "btn btn-success ml-2" %>
          <%= link_to "TIOEC", toeic_words_path, class: "btn btn-warning ml-2" %>
        </p>
      </div>
      <div class="col-12 mt-4">
        <ul class="nav nav-tabs nav-justified mb-3">
          <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Vocabulary  <span class="badge badge-secondary"><%= @count_likes %></span></a></li>
          <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
          <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
        </ul>
          <div class="row">
            <% @favorites.each_with_index do |favorite, i| %>
                <div class="col-12 col-md-6 col-lg-4 mb-2">
                  <div class="card text-center bt-3 shadow" style="padding: 25px;">
                    <%= link_to "#{(Favorite.page(params[:page]).current_page - 1)*30 + i + 1}", "#{word_path(favorite)}" %><%= favorite.content %>
                  </div>
                </div>
            <% end %>
          </div>
            <%= paginate @favorites %>
      </div>
    </div>
  </div>

app/views/users/new.html.erb
<div class="container mx-auto" style="width: 80vw">
    <div class="text-center">
      <h1>Sign up</h1>
    </div>
    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            
            <%= form_with(model:@user, local: true) do |f| %>
                <%= render 'layouts/error_messages', model: f.object %>
                
                <div class="form-group">
                    <%= f.label :name, "Name" %>
                    <%= f.text_field :name, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :email, "Email" %>
                    <%= f.email_field :email, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :password, "Password" %>
                    <%= f.password_field :password, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :password_confirmation, "Confirmation" %>
                    <%= f.password_field :password_confirmation, class: "form-control" %>
                </div>
                
                <%= f.submit "Sign up", class: "btn btn-primary btn-block" %>
                
            <% end %>
            
        </div>
    </div>
</div>

app/views/users/search.html.erb
<div class="container mx-auto" style="width: 80vw">
    <h1>ユーザー検索</h1>
    <%= form_with url: search_users_path, method: :get, local: true do |f| %>
      <%= f.text_field :name %>
      <%= f.submit "検索", class: "find" %>
    <% end %>
        <% if @users.any? %>
            <div class="row mt-3">
                <% @users.each do |user| %>
                   <div class="col-12 col-sm-6 col-md-4 mb-2">
                        <div class="card text-center pt-3 pb-3 shadow">
                            <% if user.image? %>
                                <%= image_tag user.image.url, :size => '30x30', class: "user-image mx-auto d-block" %>
                            <% else %>
                                <%= image_tag "/assets/default.jpg", :size => '30x30', class: "mx-auto d-block" %>
                            <% end %>
                            <div><%= user.name %></div>
                            <p><%= link_to 'View profile', likes_user_path(user) %></p>
                       </div>
                   </div>
                <% end%>
            <% else %>
            <p class="a mt-3"></p>
            <p class="b mt-3">上記の検索フォームでユーザー名で検索してください。</p>
           </div>
       <% end %>
       <%= paginate @users %>
</div>

app/views/users/show.html.erb
<div class="container mx-auto" style="width: 80vw">
  
  <div class="text-right">
    <%= link_to "英検の単語一覧", eiken_words_path, class: "btn btn-success" %>
    <%= link_to "Toeicの単語一覧", toeic_words_path, class: "btn btn-warning" %>
  </div>
  
  <%= form_with(model: @word, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    
    <div class="form-group">
      <%= f.label :eiken, "英検" %>
      <%= f.check_box :eiken %>
    </div>
    
    <div class="form-group">
      <%= f.label :toeic, "Toeic" %>
      <%= f.check_box :toeic %>
    </div>
    
    <div class="form-group">
      <%= f.label :content, "単語" %>
      <%= f.text_field :content, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :meaning, "意味" %>
      <%= f.text_field :meaning, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :example, "例文" %>
      <%= f.text_field :example, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :translation, "訳" %>
      <%= f.text_field :translation, class: "form-control" %>
    </div>
    
    <%= f.submit "作成", class: "btn btn-primary btn-block" %>
  <% end %>
  
  
</div>