config/routes.rb
Rails.application.routes.draw do
  
  get 'toppages/index'
  root to: 'toppages#index'
  
  get 'questions/index'
  resources :inquiries, only: [:new, :create]
  get 'introductions/index'
  get 'jobs/index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get :search, on: :collection
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  
  resources :words, only:[:show, :create, :edit, :update, :destroy] do
    collection do
      get :eiken
      get :toeic
      get :confirmation
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :favorites, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/toppages/index.html.erb
<div class="container mx-auto" style="width: 80vw">
    <div class="main-pic">
        <img class="img-fluid" src="assets/bVmPZj6wMRETLIC1599302692_1599302740.jpg">
        <p>Building up <br> your vocabulary <br> as efficiently as possible </p>
        <%= link_to "Sign up", signup_path, class: "btn btn-primary rounded signup d-none d-md-inline-block" %>
    </div>
    <div>
        <h2 class="mt-5">Buil Voca（ビルボキャ）とは？</h2>
        <p>
        Buil Vocaとは、進化し続ける英単語アプリケーションです。​<br>
        Buil Vocaは、英語試験のスペシャリストを集め、試験別に出やすい単語をまとめ、見やすくしました。Buil Vocaの教員は、皆様に実際に試験に出る英単語に触れてもらうため、英語の試験を継続的に受け続け、Buil Vocaの英単語を更新しています。<br>
        加えて、ユーザー機能で単語をお気に入りに入れることで、自分だけの単語帳を作ることができます。<br>
        ほかのユーザーのお気に入り単語も見ることができるので、お友達などとわからない単語を共有することもできます。10問チェックという単語テストもご用意しています。ぜひ、Buil Vocaを利用して、英語の試験に合格しましょう！！
        </p>
    </div>
    <div class="information mt-4">
      <h2>お知らせ</h2>
      <ul class="mt-4 overflow-auto" style="height: 70px;">
        <li>
          <span class="date">2020年10月25日</span> <span>英語試験（とーぷる）追加予定のお知らせ</span>
        </li>
        <li>
          <span class="date">2020年10月25日</span> <span>英語試験（あいえるとぅ）追加予定のお知らせ</span>
        </li>
        <li>
           <span class="date">2020年10月23日</span> <span>テスト機能を追加</span>
        </li>
        <li>
           <span class="date">2020年10月23日</span> <span>英語試験 (TIOEC) 追加</span>
        </li>
        <li>
           <span class="date">2020年10月5日</span> <span>Buil voca サービス開始</span>
        </li>
      </ul>
    </div>
    <div>
      <h2 class="mt-5">テストの種類</h2><small>(ブランドポリシーなどの問題により、実在しない試験名を使っています。)</small>
        <div class="tests row">
          <div class="col-12 col-md-6 col-lg-3">
            <div class="card shadow">
              <img class="img-fluid card-imsg-top" src="assets/thought-catalog-IjpqsMP6RzY-unsplash.jpg">
              <div class="card-body m-0 p-0">
                <div class="card-title m-3">
                  <a href="">英語の試験</a>
                </div>
                <p class="card-text m-3">上記のリンクでホームページに飛びます。</p>
                <%= link_to "単語一覧", login_path, class: "btn btn-success m-3" %>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-6 col-lg-3">
            <div class="card shadow">
              <img class="img-fluid card-imsg-top" src="assets/waldemar-brandt-U3Ptj3jafX8-unsplash.jpg">
              <div class="card-body m-0 p-0">
                <div class="card-title m-3">
                  <a href="">ティオエック（TIOEC）</a>
                </div>
                <p class="card-text m-3">上記のリンクでホームページに飛びます。</p>
                <%= link_to "単語一覧", login_path, class: "btn btn-success m-3" %>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-6 col-lg-3">
            <div class="card shadow">
              <img class="img-fluid card-imsg-top" src="assets/coming-soon-4710796_640.jpg"  style="height: 129px;">
              <div class="card-body m-0 p-0">
                <div class="card-title m-3">
                  <a href="">あいえるとぅ</a>
                </div>
                <p class="card-text m-3">お知らせをお待ちください。</p>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-6 col-lg-3">
            <div class="card shadow">
              <img class="img-fluid card-imsg-top" src="assets/coming-soon-4710796_640.jpg" style="height: 129px;">
              <div class="card-body m-0 p-0">
                <div class="card-title m-3">
                  <a href="">とーぷる</a>
                </div>
                <p class="card-text m-3">お知らせをお待ちください。</p>
              </div>
            </div>
          </div>  
        </div>
    </div>
</div>

<div class="footer">
    <footer class="mx-auto" style="width: 80vw">
      <ul class="text-center" style="list-style: none;">
        <li class="d-inline-block" style="margin-right: 15px;"><a href="#"><i class="fab fa-twitter"></i></a></li>
        <li class="d-inline-block" style="margin-right: 15px;"><a href="#"><i class="fab fa-instagram"></i></a></li>
        <li class="d-inline-block" style="margin-right: 15px;"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
      </ul>
      <div class="text-center">
        <p class="d-inline-block mr-2"><i class="fas fa-question-circle mr-2"></i><span><%= link_to "Q & A", questions_index_path %></span></p>
        <p class="d-inline-block mr-2"><i class="fas fa-chalkboard-teacher mr-2"></i><span><%= link_to "先生紹介", introductions_index_path, data: {"turbolinks" => false}%></span></p>
        <p class="d-inline-block mr-2"><i class="fas fa-user mr-2"></i><span><%= link_to "求人情報", jobs_index_path %></span></p>
        <p class="d-inline-block"><i class="fas fa-phone mr-2"></i><span><%= link_to "お問い合わせ", new_inquiry_path %></span></p>
      </div>
      <div class="text-center mt-3">
        <small>© 2020 Taka</small>
      </div>
    </footer>
</div>