config/routes.rb
Rails.application.routes.draw do
  
  get 'toppages/index'
  root to: 'toppages#index'
  
  get 'questions/index'
  resources :inquiries, only: [:new, :create]
  get 'introductions/index'
  get 'jobs/index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get :search, on: :collection
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  
  resources :words, only:[:show, :create, :edit, :update, :destroy] do
    collection do
      get :eiken
      get :toeic
      get :confirmation
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :favorites, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/word.rb
class Word < ApplicationRecord
  validates :content, presence: true, length: {maximum: 50}
  validates :meaning, presence: true, length: {maximum: 255}
  validates :example, presence: true, length: {maximum: 255}
  validates :translation, presence: true, length: {maximum: 255}
  
  
  belongs_to :user
  
  has_many :favorites
  has_many :favorited, through: :favorites, source: :user
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only:[:edit]
  
  # 今回はeikenとtoeicでルーティングを組んだので無視
  # もし英検とTOEICの単語をindexページだけで作りたいときは<link>でパラメーターを飛ばしてあげてそのパラメータで条件文を作る
  # def index
  #   if params[:eiken] == "eiken"
  #     @eiken_words = Word.where(eiken: true).page(params[:page]).per(30)
  #     @toeic_words
  #   elsif params[:toeic] == "toeic"
  #     @eiken_words
  #     @toeic_words = Word.where(toeic: true).page(params[:page]).per(30)
  #   end
  # end
  
  def eiken
    @eiken_words = Word.where(eiken: true).page(params[:page]).per(30)
  end
  
  def toeic
    @toeic_words = Word.where(toeic: true).page(params[:page]).per(30)
  end
  
  def confirmation
    word_size = 10
    @eiken_words = Word.where(eiken: true).where( 'id >= ?', rand(Word.first.id..Word.last.id - word_size) ).limit(word_size)
    @toeic_words = Word.where(toeic: true).where( 'id >= ?', rand(Word.first.id..Word.last.id - word_size) ).limit(word_size)
    @number = [1,2,3,4,5,6,7,8,9,10]
  end
  
  def show
    @word = Word.find(params[:id])
  end

  def create
    @user = current_user
    @word = current_user.words.build(word_params)
      
    if @word.save
      flash[:success] = '新しい単語を作成しました。'
      redirect_to @user
    else
      flash.now[:danger] = '単語の登録に失敗しました。'
      render "users/show"
    end
  end

  def edit
    @word = Word.find(params[:id])
  end
  
  def update
    @word = Word.find(params[:id])
    if @word.update(edit_params)
      flash[:success] = "単語の編集に成功しました。 "
      redirect_to @word
    else
      flash.now[:danger] = "単語の編集に失敗しました。"
      render :edit
    end
  end
  
  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    flash[:success] = "単語を削除しました。 "
    if @word.eiken == true
      redirect_to eiken_words_path
    else
      redirect_to toeic_words_path
    end
  end
  
  private
  
  def correct_user
    @word = current_user.words.find_by(id: params[:id])
    unless @word
      redirect_to root_url
    end
  end
  
  def word_params
    params.require(:word).permit(:content, :meaning, :example, :translation, :eiken, :toeic)
  end
  
  def edit_params
    params.require(:word).permit(:content, :meaning, :example, :translation)
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_words.html.erb
<div class-"container">
  <div class="row">
    <% words.each_with_index do |word, i| %>
      <div class="col-12 col-sm-6 col-md-4 mb-2">
        <div class="card text-center bt-3 shadow" style="padding: 25px;">
          <p><%= link_to word.content, word %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= paginate words %>

app/views/words/confirmation.html.erb
<div class="container mx-auto" style="width: 80vw">

  <h3 class="m-0">10問チェック</h3>
  
  <div class="text-right mb-3">
    <a class="reload btn btn-success">もう一度テストを受ける</a>
    <% if params[:eiken] %>
      <%= link_to "単語一覧に戻る", eiken_words_path, class: "btn btn-warning" %>
    <% elsif params[:toeic] %>
      <%= link_to "単語一覧に戻る", toeic_words_path, class: "btn btn-warning" %>
    <% end %>
  </div>
  
  <% if params[:eiken] %>
    <% @eiken_words.zip(@number) do |word, num| %>
      <div class="card shadow text-center mb-3 word is-surface <%= num %>" style="padding: 140px 70px 70px 70px;">
        <p class="card_surface"><%= word.content %><p>
        <!--ここから裏-->
        <p class="card_reverse meaning"><%= word.meaning %><p>
        <a class="btn btn-success answer" style="margin-top: 40px;" id="<%= num %>"></a>
      </div>
    <% end %>
  <% elsif params[:toeic] %>
    <% @toeic_words.zip(@number) do |word, num| %>
      <div class="card shadow text-center mb-3 word is-surface <%= num %>" style="padding: 140px 70px 70px 70px;">
        <p class="card_surface"><%= word.content %><p>
        <!--ここから裏-->
        <p class="card_reverse meaning"><%= word.meaning %><p>
        <a class="btn btn-success answer" style="margin-top: 40px;" id="<%= num %>"></a>
      </div>
    <% end %>
  <% end %>
</div>

app/views/words/edit.html.erb
<div class="container mx-auto" style="width: 80vw">
  <%= form_with(model: @word, local: true) do |f| %>
    
    
    <div class="form-group">
      <%= f.label :content, "Word" %>
      <%= f.text_field :content, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :meaning, "Meaning" %>
      <%= f.text_field :meaning, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :example, "Example" %>
      <%= f.text_field :example, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :translation, "Translation" %>
      <%= f.text_field :translation, class: "form-control" %>
    </div>
    
    <%= f.submit "編集", class: "btn btn-primary btn-block" %>
  <% end %>
</div>

app/views/words/eiken.html.erb
<div class="container mx-auto mb-3" style="width: 80vw">
  <div class="text-center mb-4">
    <h3>英語試験単語一覧</h3>
  </div>
  <div class="text-right mb-3">
    <%= link_to "単語のテスト", confirmation_words_path(eiken: "eiken"), class: "btn btn-success" %>
    <% if @eiken_words %>
      <%= link_to "Toeicの単語一覧へ",  toeic_words_path, class: "btn btn-warning" %>
    <% else %>
      <%= link_to "英検の単語一覧へ",  eiken_words_path, class: "btn btn-warning" %>
    <% end %>
  </div>
  
  <div class-"container">
    <div class="row">
      <% @eiken_words.each_with_index do |word, i| %>
        <div class="col-12 col-sm-6 col-md-4 mb-2">
          <div class="card text-center bt-3 shadow" style="padding: 25px;">
            <p><%= link_to word.content, word_path(word, eiken: "eiken") %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%= paginate @eiken_words %>
</div>

app/views/words/show.html.erb
<div class="container mx-auto" style="width: 80vw">
  <div class="card shadow p-4 text-center text-md-left">
    <div>
      <h1 class="mb-4"><%= @word.content%></h1>
      <p class="mb-3">意味：<%= @word.meaning %></p>
      <p class="mb-3">例文：<%= @word.example %></p>
      <p class="mb-3">和訳：<%= @word.translation %></p>
    </div>
    
    <% if current_user.teacher == false %>
      <%= render "favorites/favorite_button", other_word: @word %>
    <% end %>
    <div class="mb-3">
      <% if current_user.teacher == true %>
        <%= link_to "編集", edit_word_path(@word), class: "btn btn-success" %>
        <%= link_to "削除", @word , method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: "btn btn-danger" %>
      <% end %>
    </div>
    <div>
      <% if params[:eiken] %>
        <%= link_to "一覧ページへ戻る", eiken_words_path %>
      <% elsif params[:toeic]  %>
        <%= link_to "一覧ページへ戻る", toeic_words_path %>
      <% else %>
      <%= link_to "ユーザーページへ戻る", likes_user_path(current_user) %>
      <% end %>
    </div>
  </div>
</div>

app/views/words/toeic.html.erb
<div class="container mx-auto mb-3" style="width: 80vw">
  <div class="text-center mb-4">
    <h3>TIOEC単語一覧</h3>
  </div>
  <div class="text-right mb-3">
    <%= link_to "単語のテスト", confirmation_words_path(toeic: "toeic"), class: "btn btn-success" %>
    <% if @eiken_words %>
      <%= link_to "Toeicの単語一覧へ",  toeic_words_path, class: "btn btn-warning" %>
    <% else %>
      <%= link_to "英検の単語一覧へ",  eiken_words_path, class: "btn btn-warning" %>
    <% end %>
  </div>
  
  <div class-"container">
    <div class="row">
      <% @toeic_words.each_with_index do |word, i| %>
        <div class="col-12 col-sm-6 col-md-4 mb-2">
          <div class="card text-center bt-3 shadow" style="padding: 25px;">
            <p><%= link_to word.content, word_path(word, toeic: "toeic") %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%= paginate @toeic_words %>
</div>