config/routes.rb
Rails.application.routes.draw do
  
  get 'toppages/index'
  root to: 'toppages#index'
  
  get 'questions/index'
  resources :inquiries, only: [:new, :create]
  get 'introductions/index'
  get 'jobs/index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get :search, on: :collection
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  
  resources :words, only:[:show, :create, :edit, :update, :destroy] do
    collection do
      get :eiken
      get :toeic
      get :confirmation
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :favorites, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="bottom" style="background-color: #f5f5f5; height: 100px;">
  <div class="text-center pt-3">
    <ul class="text-center">
      <li class="d-inline-block" style="margin-right: 15px;"><a href="#"><i class="fab fa-twitter"></i></a></li>
      <li class="d-inline-block" style="margin-right: 15px;"><a href="#"><i class="fab fa-instagram"></i></a></li>
      <li class="d-inline-block" style="margin-right: 15px;"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
    </ul>
    <small>© 2020 Taka</small>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="area">
  <header class="mb-4 fixed-top">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <% if logged_in? %>
        <% if current_user.teacher == false %>
          <%= link_to "Buil Voca", likes_user_path(current_user), class: "navbar-brand" %>
        <% else %>
          <%= link_to "Buil Voca", user_path(current_user) , class: "navbar-brand" %>
        <% end %>
      <% else %>
        <a class="navbar-brand" href="/">Buil Voca</a>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <% if logged_in? %>
            <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link" %></li>
            <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <% if current_user.teacher == false %>
              <li class="dropdown-item"><%= link_to 'プロフィール', likes_user_path(current_user) %></li>
              <% else %>
              <li class="dropdown-item"><%= link_to 'プロフィール', user_path(current_user) %></li>
              <% end %>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to "ログアウト", logout_path, method: :delete %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to "退会", @user, data: { confirm: '本当に削除してよろしいですか？' }, method: :delete %></li>
            </ul>
          </li>
          <% else %>
            <li class="nav-item"><%= link_to "Sign up", signup_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Login", login_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buil Voca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div>
      <%= render 'layouts/flash_messages' %>
  
      <%= yield %>
      
    </div>
  </body>
</html>